name: mvu - deploy para pages

on: 
   push:
      branches:
         [ master ]
jobs:
   build:
      runs-on: ubuntu-latest

      strategy: 
         matrix: 
            node-version: [16.x] 

      steps:
         -  name: Checkout
            uses: actions/checkout@v2            

         -  name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
               node-version: ${{ matrix.node-version }}

         -  name: Install 
            run: npm install 

         -  name: Deploy
            run: |
               git config --global user.name 'Marcelo Urban'
               git config --global user.email 'mvurban@mvurban.eti.br' 
               git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
               npm run deploy